name: Pigeon App Bot

on:
  # workflow_dispatch:
  schedule:
    - cron: '30 9 * * *' # Run every day at 3 PM IST (9:45 AM UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t pigeonapp-bot .

    - name: Run Docker container
      run: |
        docker run \
          -e REDDIT_CLIENT_ID=${{ secrets.REDDIT_CLIENT_ID }} \
          -e REDDIT_CLIENT_SECRET=${{ secrets.REDDIT_CLIENT_SECRET }} \
          -e ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }} \
          -e REDDIT_USERNAME=${{ secrets.REDDIT_USERNAME }} \
          -e REDDIT_PASSWORD=${{ secrets.REDDIT_PASSWORD }} \
          pigeonapp-bot